package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"sort"
	"strings"

	"gitlab.com/mjwhitta/pathname"
)

func format(str string) string {
	if !strings.Contains(str, "_") {
		return str
	}

	str = strings.ReplaceAll(strings.ToLower(str), "_", " ")
	str = strings.ReplaceAll(strings.Title(str), " ", "")
	str = strings.ReplaceAll(str, "Crlf", "CRLF")
	str = strings.ReplaceAll(str, "Http", "HTTP")

	return str
}

func genFile(pkg string, cache map[string]string, lines [][]string) {
	var e error
	var file string = "generated.go"
	var g *os.File
	var sorted []string

	if g, e = os.Create(file); e != nil {
		fmt.Printf("Failed to create %s: %s", file, e.Error())
	}
	defer g.Close()

	g.WriteString(
		"// Code generated by tools/defines.go; DO NOT EDIT.\n",
	)
	g.WriteString("package " + pkg + "\n\n")
	g.WriteString("const (\n")

	for k := range cache {
		sorted = append(sorted, k)
	}
	sort.Slice(
		sorted,
		func(i int, j int) bool {
			return len(sorted[i]) > len(sorted[j])
		},
	)

	for _, line := range lines {
		for _, k := range sorted {
			line[1] = strings.ReplaceAll(line[1], k, cache[k])
		}

		if strings.HasPrefix(line[1], "\"") {
			g.WriteString(
				fmt.Sprintf("\t%s string = %s\n", line[0], line[1]),
			)
		} else if strings.HasPrefix(line[1], "L\"") {
			g.WriteString(
				fmt.Sprintf(
					"\t%s string = %s\n",
					line[0],
					strings.Replace(line[1], "L", "", 1),
				),
			)
		} else if strings.HasPrefix(line[1], "TEXT(") {
			line[1] = strings.Replace(line[1], "TEXT(", "", 1)
			line[1] = strings.Replace(line[1], ")", "", 1)

			g.WriteString(
				fmt.Sprintf("\t%s string = %s\n", line[0], line[1]),
			)
		} else {
			g.WriteString(
				fmt.Sprintf("\t%s uintptr = %s\n", line[0], line[1]),
			)
		}
	}

	g.WriteString(")\n")
}

func init() {
	flag.Parse()
}

func main() {
	var cache = map[string]string{
		"NULL":   "0",
		"sizeof": "len",
	}
	var lines [][]string

	if flag.NArg() == 0 {
		return
	}

	for i, arg := range flag.Args() {
		if (i == 0) || !pathname.DoesExist(arg) {
			continue
		}

		processFile(&cache, &lines, arg)
	}

	genFile(flag.Arg(0), cache, lines)
}

func processFile(
	cache *map[string]string,
	lines *[][]string,
	file string,
) {
	var b []byte
	var e error
	var f *os.File
	var fullLine string
	var tmp []string

	if f, e = os.Open(pathname.ExpandPath(file)); e != nil {
		fmt.Printf("Failed to open %s: %s", file, e.Error())
	}
	defer f.Close()

	if b, e = ioutil.ReadAll(f); e != nil {
		fmt.Printf("Failed to read %s: %s", file, e.Error())
	}

	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)

		if strings.HasSuffix(line, "\\") {
			fullLine += line[:len(line)-1]
			continue
		} else {
			fullLine += line
		}

		line = fullLine
		fullLine = ""

		if !strings.HasPrefix(line, "#define") {
			continue
		}

		line = strings.Replace(line, "#define ", "", 1)
		tmp = strings.SplitN(line, " ", 2)

		if (len(tmp) != 2) ||
			strings.Contains(tmp[0], "(") ||
			strings.Contains(tmp[0], ")") ||
			strings.Contains(tmp[1], "~") ||
			strings.Contains(tmp[1], "_(") ||
			strings.Contains(tmp[1], "DWORD") ||
			strings.Contains(tmp[1], "EXTERN_C") ||
			strings.Contains(tmp[1], "__MINGW_NAME") ||
			(tmp[0]+"W" == tmp[1]) {
			continue
		}

		(*cache)[tmp[0]] = format(tmp[0])
		*lines = append(*lines, []string{format(tmp[0]), tmp[1]})
	}
}
